all:
  hosts:
    control:
      ansible_host: 62.84.116.137
      ip: 10.10.10.10
    node1:
      ansible_host: 158.160.8.169
      ip: 10.10.20.11
    node2:
      ansible_host: 130.193.53.221
      ip: 10.10.20.12
  children:
    kube_control_plane:
      hosts:
        control:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        control:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
  vars:
    ansible_user: ubuntu
    supplementary_addresses_in_ssl_keys: ["62.84.116.137"]
